Add chinese to drop downmenu
jordan621k/viralvideos pull request #14
Opened 2020-04-20 12:35 UTC by jordan621k

2020-04-25 01:41 UTC, jordan621k commented
review LA

2020-04-27 16:22 UTC, x955199 commented on src/component/DropDownMenu.js
> +    if (this.inputId === 'languageDropDownMenu-input') {
為什麼要這個？

2020-04-27 16:24 UTC, x955199 commented on src/component/App.js
> +        document.getElementById('countryDropDownMenu-input').value =
加在 updateCountry 裡？

2020-04-27 16:26 UTC, x955199 commented on src/component/App.js
> +        document.getElementById('categoryDropDownMenu-input').value =
加在 updateCategory 裡？

2020-04-27 16:31 UTC, x955199 commented on src/component/Form.js
> +        { value: Object.entries(i18n(this.context.locale).form.dropDownOptions.country).filter((option) => { return option[1] === defaultCountryCode })[0][0], code: defaultCountryCode },
為蛇米要改這個？

2020-04-27 16:56 UTC, x955199 commented on src/component/App.js
> +        document.getElementById('languageDropDownMenu-input').value =
把這三個變一個 function ? loop i18n(this.context.locale).form.dropDownOptions 裡面的每一個dropdown

直接 document.getElementById('........DropDownMenu-input').key 就可以拿到 ....Code?

2020-04-27 16:57 UTC, x955199 commented on src/component/App.js
> +        document.getElementById('languageDropDownMenu-input').value =
不用加 countryCode, categoryCode

2020-04-27 16:58 UTC, x955199 requested changes
@jordan621k logic

2020-06-08 02:24 UTC, closed without merging